/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_dhbw_andar_CameraPreviewHandler */

#ifndef _PREVIEW
#define _PREVIEW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_dhbw_andar_CameraPreviewHandler
 * Method:    yuv420sp2rgb
 * Signature: ([BIII[B)V
 */
JNIEXPORT void JNICALL Java_com_research_gltexture_GLLayer_yuv420rgb(JNIEnv* env, jobject object,
		  jbyteArray pinArray, jint width, jint height,
		  jbyteArray poutArray, jint out_w, jint out_h);

#ifdef __cplusplus
}
#endif
#endif
